name = "mongo-realm-worker"
# type = "javascript"
compatibility_date = "2024-03-29"

account_id = "CLOUDFLARE_ACCOUNT_ID"
workers_dev = true # or zone_id = "<ZONE ID>" if you have one

main = "build/index.mjs"

[build]
command = "npm run build"

[vars]
REALM_APPID = "MONGODB_REALM_APPID"

